In [1]:
import torch

In [3]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
x.shape

torch.Size([12])

In [6]:
x.numel() # 张量里面元素的个数

12

In [9]:
X = x.reshape(3, -1) # 重新定义形状
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [13]:
torch.zeros(2, 3, 4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [15]:
torch.ones(2, 3, 4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [22]:
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [24]:
A = X
A.cumsum(axis=0) # 累加求和

tensor([[ 0,  1,  2,  3],
        [ 4,  6,  8, 10],
        [12, 15, 18, 21]])

In [64]:
# 矩阵的乘法
x = torch.arange(9, dtype=torch.float32).reshape(3, 3)
y = torch.ones(3)
x.shape, y.shape

(torch.Size([3, 3]), torch.Size([3]))

# torch.mv(A, y) 表示矩阵和向量的乘法

In [67]:
res = torch.mv(x, y)
res, res.shape

(tensor([ 3., 12., 21.]), torch.Size([3]))

# torch.mm(A, B) 表示两个矩阵的乘法

In [71]:
A = torch.arange(20, dtype=torch.float).reshape(5, 4)
B = torch.ones(4, 5)

In [73]:
torch.mm(A ,B).shape

torch.Size([5, 5])

# torch.norm(x) 就是求范数

In [75]:
torch.norm(torch.ones(3,3)) # F范数：每个元素平方，再求和

tensor(3.)

# 自动求导

In [87]:
import torch

x = torch.arange(4.0)
x.requires_grad_(True)
x.grad # 默认时None

In [88]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [89]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [91]:
x.grad == 4 * x

tensor([True, True, True, True])